// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7fLZwcdyHJW_PQ0KzXV9MCvDS_r3CLDo',
    appId: '1:863864940367:web:7275665ceb9fb3a3b8473a',
    messagingSenderId: '863864940367',
    projectId: 'controle-de-abasteciment-b4803',
    authDomain: 'controle-de-abasteciment-b4803.firebaseapp.com',
    storageBucket: 'controle-de-abasteciment-b4803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFK7hdS0BFZKWsXEZtm0tqfIVp0UvlEns',
    appId: '1:863864940367:android:e162b416872984eeb8473a',
    messagingSenderId: '863864940367',
    projectId: 'controle-de-abasteciment-b4803',
    storageBucket: 'controle-de-abasteciment-b4803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL4HtwLypydx5FnqrYKuoEXdZIIAguXvg',
    appId: '1:863864940367:ios:df08651edc56df56b8473a',
    messagingSenderId: '863864940367',
    projectId: 'controle-de-abasteciment-b4803',
    storageBucket: 'controle-de-abasteciment-b4803.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL4HtwLypydx5FnqrYKuoEXdZIIAguXvg',
    appId: '1:863864940367:ios:df08651edc56df56b8473a',
    messagingSenderId: '863864940367',
    projectId: 'controle-de-abasteciment-b4803',
    storageBucket: 'controle-de-abasteciment-b4803.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7fLZwcdyHJW_PQ0KzXV9MCvDS_r3CLDo',
    appId: '1:863864940367:web:9bebb343c9529248b8473a',
    messagingSenderId: '863864940367',
    projectId: 'controle-de-abasteciment-b4803',
    authDomain: 'controle-de-abasteciment-b4803.firebaseapp.com',
    storageBucket: 'controle-de-abasteciment-b4803.firebasestorage.app',
  );

}